# Use the README file as a reference to customize settings.

Shops::Offer:
  fields:
    default: text, price, old_price, currency, shop_id, avatar_file_name, avatar_file_size, url
    form: text, price, old_price, currency, shop_id, avatar_file_name, avatar_file_size, url
  relationships: 
  application: Application
