# Use the README file as a reference to customize settings.

Shops::Shop:
  fields:
    default: name, profile_id, text, avatar_file_name, avatar_file_size
    form: name, profile_id, text, avatar_file_name, avatar_file_size
  relationships: 
  application: Application
