# Use the README file as a reference to customize settings.

Services::Service:
  fields:
    default: name, text, profile_id, meta, avatar_file_name, avatar_file_size, published, tags
    form: name, text, profile_id, meta, avatar_file_name, avatar_file_size, published, tags
  relationships: 
  application: Application
