# Use the README file as a reference to customize settings.

ChangeRate:
  fields:
    default: CurrencyTo, CurrencyFrom, Rate, SetUpDate
    form: CurrencyTo, CurrencyFrom, Rate, SetUpDate
  relationships: 
  application: Application
