# Use the README file as a reference to customize settings.

ChatTissue:
  fields:
    default: id, text, from_profile_id, to_profile_id
    form: text, from_profile_id, to_profile_id
  relationships: 
  application: Chatting
  description: Chat tissues for all users
  filters: created_at
  order_by: -id
