# Use the README file as a reference to customize settings.

Provider:
  fields:
    default: pic, apiData, application_id
    form: pic, apiData, application_id
  relationships: 
  application: Application
