# Use the README file as a reference to customize settings.

WalletRequest:
  fields:
    default: req_status, held, sourceWallet_id, targetWallet_id, token, feed_id, currency
    form: req_status, held, sourceWallet_id, targetWallet_id, token, feed_id, currency
  relationships: 
  application: Wallets
