# Use the README file as a reference to customize settings.

Wallet:
  fields:
    default: available, holded, profile_id, IsoCurrency_id
    form: available, holded, profile_id, IsoCurrency_id
  relationships: requests
  application: Wallets
