# Use the README file as a reference to customize settings.

WalletRequest:
  fields:
    default: req_status, sourceWallet_id, targetWallet_id, token, feed_id
    form: req_status, sourceWallet_id, targetWallet_id, token, feed_id
  relationships: 
  application: Application
