# Use the README file as a reference to customize settings.

Wallet:
  fields:
    default: id, available, held, profile_id, currency
    form: id, available, held, profile_id, currency
  relationships: requests
  application: Wallets
